export const samplePrompts = [
  {
    title: "Organigramme d'Entreprise",
    text: "Crée un organigramme d'entreprise avec un PDG au sommet, trois directeurs (Technique, Marketing, Finance) sous lui, et deux employés sous chaque directeur.",
  },
  {
    title: "Processus de Développement Logiciel",
    text: "Crée un diagramme de flux pour le processus de développement logiciel agile, incluant les étapes: Planification, Conception, Développement, Tests, Déploiement et Maintenance, avec des retours possibles entre les étapes.",
  },
  {
    title: "Architecture Système",
    text: "Crée un diagramme d'architecture système pour une application web avec: frontend, backend, base de données, service d'authentification, et API tierces. Montre les connexions entre ces composants.",
  },
  {
    title: "Carte Mentale de Projet",
    text: "Crée une carte mentale pour un projet de site e-commerce avec les branches principales: Fonctionnalités, Design, Marketing, Technologie, et Budget. Ajoute 2-3 sous-branches pour chaque branche principale.",
  },
  {
    title: "Cycle de Vie d'un Produit",
    text: "Crée un diagramme cyclique montrant les étapes du cycle de vie d'un produit: Développement, Introduction, Croissance, Maturité, Déclin, et potentiellement Renouvellement.",
  },
]

// Conserver ces exemples pour la compatibilité avec le code existant
export const sampleFlowchart = JSON.stringify(
  {
    nodes: [
      {
        id: "1",
        label: "Début",
        position: { x: 250, y: 0 },
        style: { backgroundColor: "#f3f4f6", borderRadius: "8px", padding: "10px", border: "1px solid #e5e7eb" },
      },
      {
        id: "2",
        label: "Processus 1",
        position: { x: 250, y: 100 },
        style: { backgroundColor: "#dbeafe", borderRadius: "8px", padding: "10px", border: "1px solid #bfdbfe" },
      },
      {
        id: "3",
        label: "Décision",
        position: { x: 250, y: 200 },
        style: { backgroundColor: "#fef3c7", borderRadius: "8px", padding: "10px", border: "1px solid #fde68a" },
      },
      {
        id: "4",
        label: "Processus 2",
        position: { x: 100, y: 300 },
        style: { backgroundColor: "#dbeafe", borderRadius: "8px", padding: "10px", border: "1px solid #bfdbfe" },
      },
      {
        id: "5",
        label: "Processus 3",
        position: { x: 400, y: 300 },
        style: { backgroundColor: "#dbeafe", borderRadius: "8px", padding: "10px", border: "1px solid #bfdbfe" },
      },
      {
        id: "6",
        label: "Fin",
        position: { x: 250, y: 400 },
        style: { backgroundColor: "#fee2e2", borderRadius: "8px", padding: "10px", border: "1px solid #fecaca" },
      },
    ],
    edges: [
      { id: "e1-2", source: "1", target: "2", label: "Suivant" },
      { id: "e2-3", source: "2", target: "3", label: "Évaluer" },
      { id: "e3-4", source: "3", target: "4", label: "Non" },
      { id: "e3-5", source: "3", target: "5", label: "Oui" },
      { id: "e4-6", source: "4", target: "6" },
      { id: "e5-6", source: "5", target: "6" },
    ],
  },
  null,
  2,
)

export const sampleMindmap = JSON.stringify(
  {
    nodes: [
      {
        id: "1",
        label: "Concept Principal",
        position: { x: 250, y: 150 },
        style: {
          backgroundColor: "#e0f2fe",
          borderRadius: "50%",
          padding: "20px",
          width: "150px",
          height: "150px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #7dd3fc",
        },
      },
      {
        id: "2",
        label: "Idée 1",
        position: { x: 50, y: 50 },
        style: {
          backgroundColor: "#dbeafe",
          borderRadius: "50%",
          padding: "10px",
          width: "100px",
          height: "100px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #93c5fd",
        },
      },
      {
        id: "3",
        label: "Idée 2",
        position: { x: 450, y: 50 },
        style: {
          backgroundColor: "#dbeafe",
          borderRadius: "50%",
          padding: "10px",
          width: "100px",
          height: "100px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #93c5fd",
        },
      },
      {
        id: "4",
        label: "Idée 3",
        position: { x: 50, y: 250 },
        style: {
          backgroundColor: "#dbeafe",
          borderRadius: "50%",
          padding: "10px",
          width: "100px",
          height: "100px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #93c5fd",
        },
      },
      {
        id: "5",
        label: "Idée 4",
        position: { x: 450, y: 250 },
        style: {
          backgroundColor: "#dbeafe",
          borderRadius: "50%",
          padding: "10px",
          width: "100px",
          height: "100px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #93c5fd",
        },
      },
      {
        id: "6",
        label: "Sous-idée 1.1",
        position: { x: 0, y: 0 },
        style: {
          backgroundColor: "#ede9fe",
          borderRadius: "50%",
          padding: "5px",
          width: "80px",
          height: "80px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #c4b5fd",
        },
      },
      {
        id: "7",
        label: "Sous-idée 3.1",
        position: { x: 0, y: 350 },
        style: {
          backgroundColor: "#ede9fe",
          borderRadius: "50%",
          padding: "5px",
          width: "80px",
          height: "80px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          border: "2px solid #c4b5fd",
        },
      },
    ],
    edges: [
      { id: "e1-2", source: "1", target: "2", style: { stroke: "#93c5fd", strokeWidth: 2 } },
      { id: "e1-3", source: "1", target: "3", style: { stroke: "#93c5fd", strokeWidth: 2 } },
      { id: "e1-4", source: "1", target: "4", style: { stroke: "#93c5fd", strokeWidth: 2 } },
      { id: "e1-5", source: "1", target: "5", style: { stroke: "#93c5fd", strokeWidth: 2 } },
      { id: "e2-6", source: "2", target: "6", style: { stroke: "#c4b5fd", strokeWidth: 1 } },
      { id: "e4-7", source: "4", target: "7", style: { stroke: "#c4b5fd", strokeWidth: 1 } },
    ],
  },
  null,
  2,
)

export const sampleOrgChart = JSON.stringify(
  {
    nodes: [
      {
        id: "1",
        label: "PDG",
        position: { x: 250, y: 0 },
        data: { role: "Directeur Général" },
        style: {
          backgroundColor: "#fee2e2",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #fecaca",
        },
      },
      {
        id: "2",
        label: "Directeur Technique",
        position: { x: 100, y: 100 },
        data: { role: "CTO" },
        style: {
          backgroundColor: "#dbeafe",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #bfdbfe",
        },
      },
      {
        id: "3",
        label: "Directeur Marketing",
        position: { x: 400, y: 100 },
        data: { role: "CMO" },
        style: {
          backgroundColor: "#dbeafe",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #bfdbfe",
        },
      },
      {
        id: "4",
        label: "Chef de Projet",
        position: { x: 0, y: 200 },
        data: { role: "Tech Lead" },
        style: {
          backgroundColor: "#e0f2fe",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #7dd3fc",
        },
      },
      {
        id: "5",
        label: "Développeur Senior",
        position: { x: 200, y: 200 },
        data: { role: "Frontend" },
        style: {
          backgroundColor: "#e0f2fe",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #7dd3fc",
        },
      },
      {
        id: "6",
        label: "Responsable SEO",
        position: { x: 400, y: 200 },
        data: { role: "SEO Manager" },
        style: {
          backgroundColor: "#e0f2fe",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #7dd3fc",
        },
      },
      {
        id: "7",
        label: "Responsable Médias",
        position: { x: 600, y: 200 },
        data: { role: "Social Media" },
        style: {
          backgroundColor: "#e0f2fe",
          borderRadius: "4px",
          padding: "10px",
          width: "180px",
          textAlign: "center",
          border: "1px solid #7dd3fc",
        },
      },
    ],
    edges: [
      { id: "e1-2", source: "1", target: "2", animated: true },
      { id: "e1-3", source: "1", target: "3", animated: true },
      { id: "e2-4", source: "2", target: "4" },
      { id: "e2-5", source: "2", target: "5" },
      { id: "e3-6", source: "3", target: "6" },
      { id: "e3-7", source: "3", target: "7" },
    ],
  },
  null,
  2,
)

